sudo: required
services:
  - docker

global:
  # It fixes failed to install Linuxbrew on Travis-CI
  # SEE: https://stackoverflow.com/a/48398032/1545387
  - HOMEBREW_FORCE_VENDOR_RUBY=1

before_script:
  # TODO: cache docker
  - docker build -t yap.sh-ubuntu:16.04 docker --build-arg UBUNTU_VERSION=16.04
  - docker build -t yap.sh-ubuntu:18.04 docker --build-arg UBUNTU_VERSION=18.04
  - ./build.sh

jobs:
  include:
    # - &test
    #   stage: test
    #   script:
    #     - docker run -it --name yap.sh -v "$PWD/gh-pages/index.html:/yap.sh" "$IMAGE" /yap.sh
    #   env: IMAGE="yap.sh-ubuntu:16.04"

    # # - <<: *test
    # #   env: IMAGE="yap.sh-ubuntu:18.04"

    # - stage: Coverage check
    #   script: ./coverage.sh

    - stage: deploy
      provider: pages
      skip-cleanup: true
      local-dir: "./gh-pages"
      github-token: $GITHUB_TOKEN
      keep-history: true
      name: Chanwoong Kim
      email: chanwoong@chanwoong.kim
      on:
        branch: develop
