language: c
sudo: required
services:
  - docker

env:
  - IMAGE="yap.sh-ubuntu:16.04"
  # It fixes failed to install Linuxbrew on Travis-CI
  # SEE: https://stackoverflow.com/a/48398032/1545387
  - HOMEBREW_FORCE_VENDOR_RUBY=1

script:
  - docker build -t yap.sh-ubuntu:16.04 docker
  - ./build.sh
  - chmod +x ./gh-pages/index.html
  - docker run -it --name yap.sh -e USER='root' -v "$PWD/gh-pages/index.html:/yap.sh" "$IMAGE" /yap.sh

jobs:
  include:
    - stage: deploy
      local-dir: "./gh-pages"
      provider: pages
      github-token: $GITHUB_TOKEN
      name: Chanwoong Kim
      email: chanwoong@chanwoong.kim
      on:
        branch: master
