language: c
sudo: required
services:
  - docker

global:
  # It fixes failed to install Linuxbrew on Travis-CI
  # SEE: https://stackoverflow.com/a/48398032/1545387
  - HOMEBREW_FORCE_VENDOR_RUBY=1

env:
  - IMAGE="yap.sh-ubuntu:16.04"
  - IMAGE="yap.sh-ubuntu:18.04"

script:
  - docker build -t yap.sh-ubuntu:16.04 docker --build-arg UBUNTU_VERSION=16.04
  - docker build -t yap.sh-ubuntu:18.04 docker --build-arg UBUNTU_VERSION=18.04
  - ./build.sh
  - docker run -it --name yap.sh -v "$PWD/gh-pages/index.html:/yap.sh" "$IMAGE" /yap.sh

jobs:
  include:
    - stage: test
      script: ./coverage.sh

    - stage: deploy
      local-dir: "./gh-pages"
      provider: pages
      github-token: $GITHUB_TOKEN
      name: Chanwoong Kim
      email: chanwoong@chanwoong.kim
      on:
        branch: master
