FROM ubuntu:16.04

LABEL maintainer "Chanwoong Kim <chanwoong@chanwoong.kim>"

RUN useradd -ms /bin/bash kexplo
#            │└─ Set user's login shell to '/bin/bash'
#            └─ Create home directory

USER kexplo
WORKDIR /home/kexplo
